plan

diff --git a/.github/workflows/vmss.yml b/.github/workflows/vmss.yml
--- a/.github/workflows/vmss.yml
+++ b/.github/workflows/vmss.yml
@@ -5,42 +5,42 @@ on:
     branches:
       - "main"
 jobs:
-  terraform-unit-tests:
-    name: "Test"
-    runs-on: ubuntu-latest
+  # terraform-unit-tests:
+  #   name: "Test"
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
 
-      - name: Terraform Init
-        run: terraform init -backend=false
+  #     - name: Terraform Init
+  #       run: terraform init -backend=false
 
-      - name: Terraform Validate
-        run: terraform validate
+  #     - name: Terraform Validate
+  #       run: terraform validate
 
-      - name: Terraform Format
-        run: terraform fmt -check -recursive
+  #     - name: Terraform Format
+  #       run: terraform fmt -check -recursive
 
-      - name: Run Checkov action
-        id: checkov
-        uses: bridgecrewio/checkov-action@master
-        with:
-          framework: terraform
+  #     - name: Run Checkov action
+  #       id: checkov
+  #       uses: bridgecrewio/checkov-action@master
+  #       with:
+  #         framework: terraform
 
-      - name: Upload SARIF file
-        if: success() || failure()
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: results.sarif
-          category: checkov
+  #     - name: Upload SARIF file
+  #       if: success() || failure()
+  #       uses: github/codeql-action/upload-sarif@v2
+  #       with:
+  #         sarif_file: results.sarif
+  #         category: checkov
 
   terraform-plan:
     name: "Plan"
-    needs: terraform-unit-tests
+    # needs: terraform-unit-tests
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -51,7 +51,7 @@ jobs:
 
       - name: Terraform Plan
         run: terraform plan -backend=false
-        
+
   terraform-apply:
     name: "Apply"
     needs: terraform-plan
